# fly.toml app configuration file
app = "go-blog"
primary_region = "ams"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]


[http_service.tls]
alpn = ["h2", "h3"]

[services]
[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[[services.ports]]
port = 8080
handlers = ["http"]

[experimental]
enable_http3 = true

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256

